# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=255)),
                ('Is_admin', models.BooleanField(default=0)),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
                ('Updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
