# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codeupdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commituser', models.CharField(max_length=255)),
                ('svninfo', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('auditor', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=0)),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
                ('Updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='hostinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('minionid', models.CharField(max_length=255, null=True)),
                ('system', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255, null=True)),
                ('services', models.CharField(max_length=255, null=True)),
                ('status', models.BooleanField(default=1)),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
                ('Updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='saltcommandhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('minions', models.CharField(max_length=255)),
                ('miniontype', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('arg', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': '\u547d\u4ee4\u5386\u53f2',
                'verbose_name_plural': '\u547d\u4ee4\u5386\u53f2',
            },
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=255)),
                ('Is_admin', models.BooleanField(default=0)),
                ('Createtime', models.DateTimeField(auto_now_add=True)),
                ('Updatetime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
