# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_hostinfo_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='saltcommandhistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('minions', models.CharField(max_length=255)),
                ('miniontype', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=255)),
                ('arg', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': '\u547d\u4ee4\u5386\u53f2',
                'verbose_name_plural': '\u547d\u4ee4\u5386\u53f2',
            },
        ),
    ]
